### ISSUE TITLE
Not an issue - Device IP?

### ISSUE THREAD

**Issue by kaotix** [hgross/node-red-contrib-tuya-smart#1]
This isn't an issue, more of a - how the f do I do this...
I have a ton of devices on my WiFi and honestly have no idea what most of them are (or care, it's closed WiFi). I'm unable to determine what IPs my tuya sockets are using so I can't use the keys I retrieved.
Is anyone able to assist? I thought the proxy would have been so kind as to return the IPs with the device ID and keys.

**Comment by kaotix** [comment]
I ended up just comparing my "online" list and powered off the socket.
The app itself only gives me my external IP so that wouldn't work.

**Comment by hgross** [comment]
Scanning your network for open ports (TCP 6668) might help to find the relevant devices to start with.
