### ISSUE TITLE
Incorrect IP address

### ISSUE THREAD

**Issue by leeiberry** [hgross/node-red-contrib-tuya-smart#5]
the IP address assign to the tuya devices is not on the same network 

ie wifi network is 10.0.0.1   where the tuya device are allocated 1.168.198.174  

Node red is running with a Docker container .

**Comment by hgross** [comment]
This is not a problem with this node. You have to enter a correct and reachable IP address. 

If you have problems connecting to your wifi network, check out the Docker documentation on networking: https://docs.docker.com/network/

**Comment by leeiberry** [comment]
Just to clarify , I got the IP address from the Tuya app , which it seems is my external IP address..opps !
Node Red is already talking to other service on the network 
Looked on my wifi system and the devices are not listed , But Home assistant can find them ( via component)

**Comment by leeiberry** [comment]
sorry found ip  address , device listed as ESP -mac
